version: "2.1"
services:
    app:
        image: assistant/assistant
        restart: always
        environment:
            - TRANSMISSION_URL=IP:LOGIN:PASSWORD
            - TELEGRAM_BOT_TOKEN=TOKEN
        logging:
            driver: json-file
            options:
                max-file: "4"
                max-size: "4m"

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.27.3.0/24